export const TASK_ACTIONS = {
    CREATE_TASK: "CREATE_TASK",
    COMPLETE_TASK: "COMPLETE_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    DELETE_TASK: "DELETE_TASK",
    CLEAR_COMPLETED_TASKS:"CLEAR_COMPLETED_TASKS"

}